<?xml version="1.0"?>

<!-- Fabrizia Auletta -->
<!-- fabrizia.auletta@bristol.ac.uk -->
<!-- June 2020 -->

<robot name="agent_diff_drive" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find agent_description)/urdf/herd_robot_macro.xacro" /> 

  
  
	<!--Actual body/chassis of the robot-->
	<link name="target_0_base_link">
		<inertial>
			<mass value="${base_mass}" />
			<origin xyz="0 0 0" />
			<box_inertia  m="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}"/>
		</inertial>    
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://herd_description/meshes/chassis.dae"/>
			</geometry>
		</visual>  
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
	<box size="${base_length} ${base_width} ${base_height}"/>
			</geometry>
		</collision>     
	</link>

	<xacro:caster_joint 
		name="caster_front_link"
		parent="target_0_base_link"
		child="caster_front_link">
		<origin xyz="-0.15 0.0 -0.15" rpy="${-M_PI/2} 0 0"/>
	</xacro:caster_joint>

	<xacro:caster_link
		name="caster_front_link">
			<origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
	</xacro:caster_link>
	

	
	
	<wheel fb="front" lr="right" parent="target_0_base_link" translateX="1" translateY="1" flipY="1"/>
	<wheel fb="front" lr="left" parent="target_0_base_link" translateX="1" translateY="-1" flipY="1"/>
	
	  <gazebo reference="front_right_wheel">
        <material>Gazebo/Green</material>
         </gazebo>
         
         <gazebo reference="front_left_wheel">
        <material>Gazebo/Green</material>
         </gazebo>

  
  <!-- Differential drive controller  -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <legacyMode>true</legacyMode>
      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>1</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>front_left_wheel_joint</leftJoint> 
      <rightJoint>front_right_wheel_joint</rightJoint>
      <wheelSeparation>${2*base_width}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>target_0_cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>target_0_base_link</robotBaseFrame>
    </plugin>
  </gazebo> 
  

 
</robot>
